export const WS_EVENTS = {
  USER_ONLINE: 'USER:ONLINE',
  ROOM_JOIN: 'ROOM:JOIN',
  MSG_SEND: 'MSG:SEND',
  MSG_TYPING: 'MSG:TYPING',
};

export const WS_LISTENERS = {
  USER_ONLINE: 'USER:ONLINE',
  USER_OFFLINE: 'USER:OFFLINE',
  MSG_SELF_DELIVERED: 'MSG:SELF:DELIVERED',
  MSG_DELIVERED: 'MSG:DELIVERED',
};
